server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:booking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: rashasoftleave@gmail.com
    password: qmhmzgzfjapxplde
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
